AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SupportDesk API - Lambda + API Gateway + RDS PostgreSQL

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: provided.al2023
    Architectures:
      - x86_64
    Environment:
      Variables:
        DB_HOST: !Ref DBHost
        DB_PORT: !Ref DBPort
        DB_USER: !Ref DBUser
        DB_PASSWORD: !Ref DBPassword
        DB_NAME: !Ref DBName
        DB_SCHEMA: mysupporttickr
        DB_SSLMODE: require
        JWT_SECRET: !Ref JWTSecret
        FRONTEND_URL: !Ref FrontendURL

Parameters:
  DBHost:
    Type: String
    Description: RDS PostgreSQL hostname
  DBPort:
    Type: String
    Default: '5432'
  DBUser:
    Type: String
    Default: supportdesk
  DBPassword:
    Type: String
    NoEcho: true
  DBName:
    Type: String
    Default: supporttickr
  JWTSecret:
    Type: String
    NoEcho: true
    Default: change-me-in-production-to-a-long-random-string
  FrontendURL:
    Type: String
    Default: '*'
    Description: Frontend URL for CORS (e.g., https://yourdomain.com)
  VpcId:
    Type: String
    Description: VPC ID for Lambda (e.g. vpc-0abc123def456)
  SubnetIds:
    Type: CommaDelimitedList
    Description: Subnet IDs for Lambda (comma-separated, e.g. subnet-xxx,subnet-yyy)

Resources:
  SupportDeskApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins:
          - !Ref FrontendURL
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
        MaxAge: 300

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bootstrap
      CodeUri: ../
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            ApiId: !Ref SupportDeskApi
            Path: /{proxy+}
            Method: ANY
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds: !Ref SubnetIds
    Metadata:
      BuildMethod: makefile

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for SupportDesk Lambda function
      VpcId: !Ref VpcId

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${SupportDeskApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt ApiFunction.Arn
